version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: sql
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: backend
      MYSQL_USER: root
    volumes:
      - ./bin/_database:/var/lib/mysql
#  server:
#    image: node
#    container_name: nest
#    restart: always
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    ports:
#      - 5000:5000
#      - 9229:9229
volumes:
  db_data: {}
  wordpress_data: {}