version: "3.9"
services:
#  db:
#    image: mysql:5.7
#    container_name: sql
#    restart: always
#    tty: true
#    env_file:
#      - .env
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: backend
#      MYSQL_USER: root
#      MYSQL_PASSWORD: admin
  server:
    image: node:14
    container_name: nest
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: npm run dev
    env_file:
      - .env
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

#    image: node:14
#    container_name: nest
#    restart: always
#    tty: true
##    links:
##      - db
#    build:
#      context: ./
#    env_file:
#      - .env
#    volumes:
#      - "./backend :/backend"
#      - "/backend/node_modules :/node_modules"
#    ports:
#      - "5000:5000"
#      - "9229:9229"
volumes:
  db_data: {}
  wordpress_data: {}