version: "3.9"
services:
#  db:
#    image: mysql:5.7
#    container_name: sql
#    restart: always
#    tty: true
#    env_file:
#      - .env
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: backend
#      MYSQL_USER: root
#      MYSQL_PASSWORD: admin
  server:
    image: node:14
    container_name: nest
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
volumes:
  db_data: {}
  wordpress_data: {}