version: "3.9"
services:
  db:
    image: mysql:8.0.27
    container_name: sql
    restart: always
    env_file:
      - .env
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_USER: MYSQL_USER
      MYSQL_DATABASE: MYSQL_DB
      MYSQL_ROOT_HOST: MYSQL_HOST
    volumes:
      - ./bin/_database:/var/lib/mysql
  server:
    image: node
    container_name: nest
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 9229:9229
volumes:
  db_data: {}
  wordpress_data: {}